title: A course
tagline: A brand new course on Learning Lab
description: This is a demo course
template:
  repo: a-course-template
  name: a-course
before:
  - type: createIssue
    title: Welcome!
    body: new-issue.md
steps:
  - title: 'Step #1'
    description: Assign yourself to this issue to continue.
    event: issues.assigned
    link: '{{ repoUrl }}'
    actions:
      - type: createPullRequest
        title: 'PullRequest #2'
        body: responses-step-2
        head: step1
        base: master
  - title: 'Step #2'
    description: Merge this Pull Request
    event: pull_request.closed
